# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Kuiiz
email: bsilva.se@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Oi Internet, seja bem vindo ! Pode entrar, o espaço é gratuito.
url: "http://kuiiz.com/br" # the base hostname & protocol for your site
sobre: /sobre
contato: /contato

baseurl: "" # the subpath of your site, e.g. /blog
github_username:  bstk
facebook_username: bsilvablog.se@gmail.com

sass:
  style: compressed

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown

# Mailchimp Newsletter URL if any, then uncomment next line and add a url.
# mailchimp: ""

# Uncomment and change values to add Google Analytics
# ga_id: UA-47902363-1
# ga_domain: bitwiser.in

# Disqus forumname. Uncomment and change the value if you want to enable Disqus commenting in blog posts.
disqus: BrunoLuz
